# Generated by Django 4.2.7 on 2026-03-31 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('num_lanes', models.PositiveIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrafficSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('NORTH', 'North'), ('SOUTH', 'South'), ('EAST', 'East'), ('WEST', 'West')], max_length=10)),
                ('current_phase', models.CharField(choices=[('RED', 'Red'), ('YELLOW', 'Yellow'), ('GREEN', 'Green')], default='RED', max_length=10)),
                ('green_duration', models.PositiveIntegerField(default=30, help_text='seconds')),
                ('red_duration', models.PositiveIntegerField(default=60)),
                ('yellow_duration', models.PositiveIntegerField(default=5)),
                ('last_changed', models.DateTimeField(auto_now=True)),
                ('is_operational', models.BooleanField(default=True)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='core.intersection')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Car'), ('TRUCK', 'Truck'), ('MOTORCYCLE', 'Motorcycle'), ('BUS', 'Bus')], default='CAR', max_length=12)),
                ('average_speed', models.FloatField(default=0.0, help_text='km/h')),
                ('congestion_level', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_counts', to='core.intersection')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_counts', to='core.trafficsignal')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('ACCIDENT', 'Accident'), ('BREAKDOWN', 'Breakdown'), ('ROADBLOCK', 'Roadblock'), ('EMERGENCY', 'Emergency'), ('WEATHER', 'Weather')], max_length=15)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.intersection')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('DANGER', 'Danger'), ('SUCCESS', 'Success')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('intersection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.intersection')),
            ],
        ),
        migrations.CreateModel(
            name='TrafficAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.PositiveIntegerField()),
                ('avg_vehicle_count', models.FloatField(default=0)),
                ('peak_count', models.PositiveIntegerField(default=0)),
                ('avg_speed', models.FloatField(default=0)),
                ('avg_congestion_score', models.FloatField(default=0)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.intersection')),
            ],
            options={
                'unique_together': {('intersection', 'date', 'hour')},
            },
        ),
    ]
